import { boolean, integer, numeric, pgTable, serial, text, timestamp, uniqueIndex } from "drizzle-orm/pg-core";

const createdAt = timestamp("created_at", { withTimezone: true }).defaultNow().notNull();

export const categories = pgTable("categories", { id: serial("id").primaryKey(), name: text("name").notNull(), slug: text("slug").notNull(), image: text("image"), createdAt }, (table) => [uniqueIndex("categories_slug_unique").on(table.slug)]);
export const products = pgTable("products", { id: serial("id").primaryKey(), name: text("name").notNull(), slug: text("slug").notNull(), description: text("description").notNull(), ingredients: text("ingredients"), price: numeric("price", { precision: 10, scale: 2 }).notNull(), offerPrice: numeric("offer_price", { precision: 10, scale: 2 }), weight: text("weight").notNull(), categoryId: integer("category_id").references(() => categories.id), image: text("image"), stock: integer("stock").notNull().default(0), featured: boolean("featured").notNull().default(false), bestseller: boolean("bestseller").notNull().default(false), createdAt }, (table) => [uniqueIndex("products_slug_unique").on(table.slug)]);
export const combos = pgTable("combos", { id: serial("id").primaryKey(), title: text("title").notNull(), slug: text("slug").notNull(), price: numeric("price", { precision: 10, scale: 2 }).notNull(), discount: numeric("discount", { precision: 10, scale: 2 }).notNull().default("0"), image: text("image"), createdAt }, (table) => [uniqueIndex("combos_slug_unique").on(table.slug)]);
export const comboItems = pgTable("combo_items", { id: serial("id").primaryKey(), comboId: integer("combo_id").notNull().references(() => combos.id, { onDelete: "cascade" }), productId: integer("product_id").notNull().references(() => products.id), quantity: integer("quantity").notNull().default(1) });
export const customers = pgTable("customers", { id: serial("id").primaryKey(), name: text("name").notNull(), phone: text("phone").notNull(), email: text("email"), createdAt }, (table) => [uniqueIndex("customers_phone_unique").on(table.phone)]);
export const orders = pgTable("orders", { id: serial("id").primaryKey(), orderNumber: text("order_number").notNull(), customerId: integer("customer_id").references(() => customers.id), customerName: text("customer_name").notNull(), phone: text("phone").notNull(), email: text("email"), address: text("address").notNull(), total: numeric("total", { precision: 10, scale: 2 }).notNull(), paymentStatus: text("payment_status").notNull().default("pending"), orderStatus: text("order_status").notNull().default("placed"), razorpayOrderId: text("razorpay_order_id"), createdAt }, (table) => [uniqueIndex("orders_number_unique").on(table.orderNumber)]);
export const orderItems = pgTable("order_items", { id: serial("id").primaryKey(), orderId: integer("order_id").notNull().references(() => orders.id, { onDelete: "cascade" }), productId: integer("product_id").references(() => products.id), name: text("name").notNull(), quantity: integer("quantity").notNull(), price: numeric("price", { precision: 10, scale: 2 }).notNull() });
export const coupons = pgTable("coupons", { id: serial("id").primaryKey(), code: text("code").notNull(), discountType: text("discount_type").notNull(), value: numeric("value", { precision: 10, scale: 2 }).notNull(), active: boolean("active").notNull().default(true), createdAt }, (table) => [uniqueIndex("coupons_code_unique").on(table.code)]);
export const reviews = pgTable("reviews", { id: serial("id").primaryKey(), productId: integer("product_id").references(() => products.id), customerName: text("customer_name").notNull(), rating: integer("rating").notNull(), content: text("content").notNull(), approved: boolean("approved").notNull().default(false), createdAt });
export const banners = pgTable("banners", { id: serial("id").primaryKey(), title: text("title").notNull(), image: text("image"), href: text("href"), active: boolean("active").notNull().default(true), createdAt });
